language: php

matrix:
  include:
    - php: 7.1
      env: DB=sqlite; TYPE=coverage
    - php: 7
      env: DB=mysql

sudo: false

install:
  - if [ "$DB" == "mysql" ]; then mysql -e 'create database spenden;'; fi
  - travis_retry composer install

script: composer ci

after_success: bash tests/uploadCoverage.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
