language: php

php:
  - 5.5
  - 7

sudo: false

install: travis_retry composer install --prefer-source

script: composer ci

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
