language: php

matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=mysql
    - php: 7
      env: DB=sqlite
    - php: 7
      env: DB=mysql

sudo: false

install:
  - if [ "$DB" == "mysql" ]; then mysql -e 'create database spenden;'; fi
  - travis_retry composer install

script: composer ci

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
