app:
  build: ./
  volumes:
    - ./:/code
  links:
    - database
  working_dir: /code

database:
  image: mysql:5
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=fundraising
    - MYSQL_PASSWORD=fundraising
    - MYSQL_DATABASE=fundraising
  expose:
    - "3306"
